POST http://localhost:3000/init
Content-Type: application/json

{
    "secret": "cisco"
}
###

GET http://localhost:3000/users
###

GET http://localhost:3000/users/alldata
###

DELETE http://localhost:3000/users/1
###

POST http://localhost:3000/users HTTP/1.1
content-type: application/json

{
    "nome": "Andrea",
    "cognome": "Trentini",
    "data_nascita": "1968-04-08",
    "email": "andrea.trentini@marconirovereto.it",
    "username": "andtrentini",
    "password": "pippo"

}
###

PUT http://localhost:3000/users/2 HTTP/1.1
content-type: application/json

{
    "nome": "Luca",
    "cognome": "Boschi",
    "data_nascita": "1968-04-08",
    "email": "andrea.trentini@marconirovereto.it",
    "username": "andtrentini",
    "password": "pippo"
}